# Generated by Django 5.2 on 2025-07-05 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapplication', '0002_subject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
