# Generated by Django 5.2 on 2025-07-08 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapplication', '0010_hostel_hostelbooking_hostelfeestructure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelbooking',
            name='bed_number',
        ),
        migrations.RemoveField(
            model_name='hostelbooking',
            name='room',
        ),
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('bed_name', models.CharField(max_length=25)),
                ('is_available', models.BooleanField(default=True)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('bunk_top', 'Bunk Bed (Top)'), ('bunk_bottom', 'Bunk Bed (Bottom)')], default='single', max_length=20)),
                ('facilities', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='coreapplication.hostelroom')),
            ],
            options={
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='hostelbooking',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='coreapplication.hostelbed'),
            preserve_default=False,
        ),
    ]
