# Generated by Django 5.2 on 2025-07-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapplication', '0011_remove_hostelbooking_bed_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_type', models.CharField(choices=[('online', 'Reported Online'), ('physical', 'Reported Physical'), ('erp', 'Reported Via ERP')], default='online', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reports', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='coreapplication.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='coreapplication.student')),
            ],
            options={
                'ordering': ['-reported_date'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.DeleteModel(
            name='StudentReport',
        ),
    ]
