# Generated by Django 5.2 on 2025-07-18 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapplication', '0012_studentreporting_delete_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_/ allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, @, ., +, -, _, and / characters only.', regex='^[\\w.@+\\-/]+$')]),
        ),
    ]
