# Generated by Django 5.2 on 2025-07-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapplication', '0013_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoomTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('reason', models.CharField(choices=[('maintenance', 'Room Maintenance'), ('student_request', 'Student Request'), ('administrative', 'Administrative'), ('disciplinary', 'Disciplinary'), ('medical', 'Medical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='coreapplication.hostelbed')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_transfers', to='coreapplication.student')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='coreapplication.hostelbed')),
            ],
        ),
    ]
